[package]
name = "sync-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2.0.12"
protocol = { path = "../protocol" }
serde_json = "1.0.141"
zstd = "0.13.3"
