[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
argon2 = "0.5.3"
blake3 = "1.5"
rand = "0.9.1"
rand_core = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"
zeroize = "1.8.1"
